server:
  port: 8040

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cliente-service
          uri: lb://cliente-service
          predicates:
            - Path=/clientes/**
        - id: proveedor-service
          uri: lb://proveedor-service
          predicates:
            - Path=/proveedores/**
        - id: shopping-service
          uri: lb://shopping-service
          predicates:
            - Path=/invoices/**