server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cliente-service
          uri: lb://cliente-service
          predicates:
            - Path=/clientes/**
        - id: proveedor-service
          uri: lb://proveedor-service
          predicates:
            - Path=/proveedores/**
        - id: membresia-service
          uri: lb://membresia-service
          predicates:
            - Path=/membresias/**
        - id: reserva-service
            uri: lb://reserva-service
            predicates:
              - Path=/reservas/**